services:
  postgres_db:
    image: postgres
    ports:
      - 5455:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: warsztaty
      POSTGRES_USER: warsztaty
      POSTGRES_DB: warsztaty

volumes:
  postgres:
